### ISSUE TITLE
getProducts - add random sort

### ISSUE THREAD

**Issue by nickff** [craftsmancoding/moxycart#36]
Add a random sort option, as well as an option to not include the product currently being viewed. This will help when using the snippet to generate a list of "recommended products" like we have at the bottom of this page - http://hawkinsnewyork.com/shop/rod-weave-chair

**Comment by fireproofsocks** [comment]
I had to adjust the code in several places:

BaseModel::quoteSort() -- needed extra code to avoid quoting the "RAND()" sort option.

I also copied some of the code from the Query snippet (see https://github.com/craftsmancoding/query/blob/master/elements/snippets/query.php) to allow for some snippet-syntax filters like "NOT EQUALS":

```
&sku:ne=`xyz`
````

So you can filter out the current product by doing something like:

````
[[getProducts? &product_id:ne=`[[+product_id]]` &sort=`RAND()`]]
````

531691d..8ea5147  master -> master
